### ISSUE TITLE
AUTHORS/CONTRIBUTORS: Incomplete

### ISSUE THREAD

**Issue by cznic** [cznic/sqlite#14]
@steffengy I just noticed you're not listed. Sorry I missed that, please add yourself, thank you.

**Comment by cznic** [comment]
That was fast ;-)

**Comment by steffengy** [comment]
Sorry seems I thought that I already was in there for sqlite.

**Comment by cznic** [comment]
I checked the history and it seems you were never listed, AFAICS.
